### ISSUE TITLE
Fix uv command not found error in Starship prompt

### ISSUE THREAD

**Issue by jitsejan** [jitsejan/dotfiles#20]
## Problem
Fish shell shows error when Starship prompt tries to execute `uv` command:

```
fish: Unknown command: uv
```

## Root Cause
Starship configuration in `.config/starship.toml` has a custom `uv` section (lines 65-70) that runs `uv --version` when it detects `uv.lock` files, but the `uv` tool is not installed.

```toml
[custom.uv]
command = 'uv --version | head -n1 | awk "{print \$2}"'
when = 'test -f uv.lock'
format = '[ ⚡ uv v$output ]($style)'
style = "fg:bright-blue"
ignore_timeout = true
```

## Solution Options
1. **Add uv to Brewfile**: Add `brew "uv"` to install via Homebrew
2. **Install via script**: Run `curl -sSf https://astral.sh/uv/install.sh | sh`
3. **Remove from config**: Comment out the uv section if not needed

## Recommended Fix
Add `uv` to the Brewfile in the Core Development Tools section since it's already referenced in the Python tooling setup.
